apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: pw-staging
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta2
    kind: AWSManagedControlPlane
    name: pw-staging-control-plane
  infrastructureRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta2
    kind: AWSManagedCluster
    name: pw-staging
---
kind: AWSManagedCluster
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
metadata:
  name: pw-staging
spec: {}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: AWSManagedControlPlane
metadata:
  name: pw-staging-control-plane
  namespace: default
spec:
  region: us-east-1
  sshKeyName: capi-eks
  version: v1.28
  disableVPCCNI: true
  network:
    vpc:
      id: vpc-07733c911327481c0
      cidrBlock: 10.254.128.0/19
      internetGatewayId: igw-0a271f183ad39aec3
    subnets:
    - id: subnet-0285f5f368ebe92f5
    - id: subnet-04a3ea8069c5c5996
    - id: subnet-0518b2031d134a71f
  addons:
    - name: "coredns"
      version: "v1.11.1-eksbuild.6"
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: default-machine-pool
  namespace: default
spec:
  clusterName: capi-eks
  replicas: 1
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: capi-eks
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSManagedMachinePool
        name: default-machine-pool
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedMachinePool
metadata:
  name: default-machine-pool
  namespace: default
spec:
  subnetIDs:
    - subnet-0285f5f368ebe92f5
    - subnet-04a3ea8069c5c5996
    - subnet-0518b2031d134a71f
