apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: capi-eks
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta2
    kind: AWSManagedControlPlane
    name: capi-eks-control-plane
  infrastructureRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta2
    kind: AWSManagedControlPlane
    name: capi-eks-control-plane
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: AWSManagedControlPlane
metadata:
  name: capi-eks-control-plane
  namespace: default
spec:
  region: us-east-1
  sshKeyName: capi-eks
  version: v1.29.0
  network:
    vpc:
      id: vpc-07733c911327481c0
      cidrBlock: 10.254.128.0/19
      internetGatewayId: igw-0a271f183ad39aec3
    subnets:
    - id: subnet-0285f5f368ebe92f5
    - id: subnet-04a3ea8069c5c5996
    - id: subnet-0518b2031d134a71f
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: capi-eks-pool-0
  namespace: default
spec:
  clusterName: capi-eks
  replicas: 2
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: capi-eks
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSManagedMachinePool
        name: capi-eks-pool-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedMachinePool
metadata:
  name: capi-eks-pool-0
  namespace: default
spec: {}
