apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-nginx
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc' #Replace the API endpint URL of your EKS cluster
  source:
    path: workload/aws-eks
    repoURL: 'https://github.com/kasun-bandara/eks-ec2-clusterapi-gitops'
    targetRevision: HEAD
  project: default #You can give a project name here
  syncPolicy:
    automated:
      allowEmpty: true
